import { Project, Capability, ProcessStep, MetricItem, FormationInfo } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'ms-word-essentials',
    name: 'MS Word (Documents & Career)',
    category: 'MS Office',
    iconName: 'FileText',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1600&q=80',
    tall: true,
    year: 'Skill Module 01',
    client: 'Document Master',
    summary: 'Format professional resumes, formal letters, college assignments, reports, and export print-ready PDF files.',
    details: 'Master Microsoft Word from the ground up: adjust margins, format typography hierarchy, apply paragraph alignments and line spacing, insert structured tables and numbered bullet lists, check grammar, add headers & footers, and export pristine PDF documents ready for job applications and academic submissions.',
    awards: ['Resume & Cover Letter Templates', 'Table & Alignment Formatting', 'Print-Ready PDF Export'],
    metrics: 'Universal Office Standard, Resume & Letter Formatting, 100% Practical',
    techStack: ['Microsoft Word', 'Font Styling', 'Page Layout & Margins', 'Tables & Bulleting', 'PDF Generation'],
  },
  {
    id: 'ms-excel-spreadsheets',
    name: 'MS Excel (Data & Spreadsheets)',
    category: 'MS Office',
    iconName: 'Table',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&q=80',
    tall: false,
    year: 'Skill Module 02',
    client: 'Data & Budgeting',
    summary: 'Build personal budgets, calculate student scores, track expenses, use essential formulas (=SUM, =AVG), and make charts.',
    details: 'Demystify spreadsheets and conquer numbers with ease. Learn how to set up clean rows and columns, format currencies and dates, freeze header rows, use foundational formulas (=SUM, =AVERAGE, =COUNT, =IF), sort and filter datasets, and generate visual bar/pie charts to present insights clearly.',
    awards: ['Essential Formulas (=SUM, =AVG)', 'Personal & Business Budgeting', 'Automated Charts & Graphs'],
    metrics: 'Automate Math & Budgets, Master 10 Core Formulas, Zero Math Fear',
    techStack: ['Microsoft Excel', 'Cell Formulas', 'Budget Tables', 'Data Sorting & Filters', 'Charts & Visuals'],
  },
  {
    id: 'ms-powerpoint-presentations',
    name: 'PowerPoint (Visual Presentations)',
    category: 'MS Office',
    iconName: 'Presentation',
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1600&q=80',
    tall: false,
    year: 'Skill Module 03',
    client: 'Visual Storytelling',
    summary: 'Design compelling slide presentations for college seminars, job interviews, client pitches, and team meetings.',
    details: 'Transform boring bullet lists into memorable visual slideshows. Learn visual hierarchy principles, choose contrasting color palettes, add clean icons and photography, utilize smart slide layouts, apply tasteful transitions, and practice using Presenter View to deliver confident speeches without getting lost.',
    awards: ['Modern Slide Layout Principles', 'Seminar & Pitch Deck Design', 'Presenter View & Transitions'],
    metrics: 'Engaging Slide Decks, High-Impact Presentations, Student & Job Ready',
    techStack: ['PowerPoint', 'Slide Master Layouts', 'Visual Hierarchy', 'Transitions & Timing', 'Presenter Mode'],
  },
  {
    id: 'web-development-html-css',
    name: 'Web Development (HTML/CSS)',
    category: 'Web Development',
    iconName: 'Code2',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1600&q=80',
    tall: false,
    year: 'Skill Module 04',
    client: 'Web Foundations',
    summary: 'Build your very first real webpage from scratch using HTML structure, CSS styling, colors, buttons, and layouts.',
    details: 'Take your first step into technology creation. Understand how web browsers read HTML tags (headings, paragraphs, images, links, buttons) and how CSS breathes life into them with colors, borders, font styles, padding, margins, and mobile-friendly layouts. Gain true technical literacy by seeing how modern websites work behind the scenes.',
    awards: ['First Live Webpage Project', 'HTML5 Semantic Tags', 'CSS Styling & Box Model'],
    metrics: 'Hands-On Code Creation, Foundation for Future Tech, Beginner Friendly',
    techStack: ['HTML5 Tags', 'CSS3 Styling', 'Box Model & Colors', 'Responsive Layout', 'Browser DevTools'],
  },
  {
    id: 'canva-design-graphics',
    name: 'Canva for Design (Visual Graphics)',
    category: 'Design & Graphics',
    iconName: 'Palette',
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1600&q=80',
    tall: false,
    year: 'Skill Module 05',
    client: 'Creative Studio',
    summary: 'Create eye-catching social media posters, YouTube thumbnails, project covers, and stylish resumes with zero design experience.',
    details: 'Unlock your creative superpower without expensive, complicated software. Learn how to navigate Canva templates, customize typography and color palettes, manipulate images and remove backgrounds, arrange elements with precision alignment, and export high-resolution PNGs, JPEGs, and print-ready PDFs for any project.',
    awards: ['Social Media & Poster Design', 'Custom Color & Font Palette', 'High-Res Multi-Format Export'],
    metrics: 'No Design Background Needed, 100s of Templates, Instant Professional Look',
    techStack: ['Canva Studio', 'Visual Composition', 'Social Media Graphics', 'Resume Formatting', 'Print & Web Export'],
  },
  {
    id: 'basic-ai-tools-productivity',
    name: 'Basic AI Tools (Daily Productivity)',
    category: 'AI & Smart Tools',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1600&q=80',
    tall: false,
    year: 'Skill Module 06',
    client: 'Smart Assistant',
    summary: 'Use ChatGPT, Google Gemini, and modern AI assistants to study faster, draft emails, summarize documents, and brainstorm.',
    details: 'Turn artificial intelligence into your personal 24/7 learning tutor and productivity sidekick. Learn the art of clear prompting, ask AI to explain difficult concepts in simple terms, summarize lengthy PDF articles, draft polite professional emails, brainstorm creative ideas for assignments, and learn safe, ethical AI practices.',
    awards: ['Prompt Writing Playbook', 'Instant Study Summaries', 'Email & Writing Assistant'],
    metrics: 'Save 10+ Hours Weekly, Modern AI Literacy, Boost Daily Confidence',
    techStack: ['ChatGPT & Gemini', 'Effective Prompting', 'Document Summarization', 'Idea Brainstorming', 'Smart Workflows'],
  },
];

export const CAPABILITIES: Capability[] = [
  {
    id: 'cap-1',
    number: '01',
    title: 'Daily Operating System & Navigation',
    description: 'Master everyday desktop tasks in Windows 10 & 11: navigating the Start Menu, split-screen multitasking with Snap layouts, managing taskbar apps, and personalizing daily audio & Wi-Fi settings.',
    tags: ['Start Menu & Quick Search', 'Split-Screen Multitasking', 'Display, Audio & Wi-Fi Setup', 'Taskbar App Pinning'],
  },
  {
    id: 'cap-2',
    number: '02',
    title: 'Daily Speed & Essential Shortcuts',
    description: 'Save valuable time in daily life with muscle-memory hotkeys: [Win]+[V] multi-clipboard history, [Win]+[Shift]+[S] instant snip screenshots, [Alt]+[Tab] app switcher, and instant undo/redo keys.',
    tags: ['[Win] + [V] Multi-Clipboard', '[Win] + [Shift] + [S] Snip Tool', '[Alt] + [Tab] Fast Switcher', '[Ctrl] + [Z] / [Y] Undo & Redo'],
  },
  {
    id: 'cap-3',
    number: '03',
    title: 'Daily Office & Academic Paperwork',
    description: 'Create polished resumes and college assignments in Word, calculate household budgets and student marks in Excel, and craft compelling presentation decks in PowerPoint for classes and jobs.',
    tags: ['Word Resumes & Formal Letters', 'Excel Household Budgets', 'PowerPoint Slide Decks', 'PDF Printing & Exporting'],
  },
  {
    id: 'cap-4',
    number: '04',
    title: 'Organizing Personal & Work Files',
    description: 'Never misplace an important document, photo, or invoice again. Organize logical folder trees, understand file types (.docx, .pdf), zip compress attachments, and use flash drives safely.',
    tags: ['Folder Hierarchy Mastery', 'ZIP Archive Compression', 'Safe USB Removal', 'Cloud Backup Sync'],
  },
  {
    id: 'cap-5',
    number: '05',
    title: 'Daily Internet, Email & Online Safety',
    description: 'Search like an expert on Google, manage busy browser tabs, compose courteous professional emails in Gmail, spot spam and fake links, and keep personal accounts safe with Two-Factor Authentication.',
    tags: ['Tab & Bookmark Hacks', 'Professional Email Writing', 'Spam & Scam Spotting', '2-Factor Account Protection'],
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    title: 'Desktop & Mouse Confidence',
    phase: 'Day 1: Fundamentals',
    description: 'Master turning on your computer safely, mouse clicking/right-clicking, navigating the Windows Start Menu, and finding any application in seconds.',
  },
  {
    number: '02',
    title: 'Files, Folders & Speed Hotkeys',
    phase: 'Day 2: Speed & Organization',
    description: 'Organize your documents neatly, learn [Win] + [V] clipboard history, take instant screenshots with [Win] + [Shift] + [S], and never lose a file.',
  },
  {
    number: '03',
    title: 'MS Office & Professional Email',
    phase: 'Day 3: Productivity & Web',
    description: 'Draft neat Word documents, calculate sums in Excel, compose clear professional emails in Gmail, add attachments, and search the web effectively.',
  },
  {
    number: '04',
    title: 'Digital Safety & Component Basics',
    phase: 'Day 4: Security & Hardware',
    description: 'Set up strong passwords, enable 2-Factor Authentication (2FA), spot phishing scams, and understand simple CPU/RAM/SSD specs when buying a PC.',
  },
];

export const METRICS: MetricItem[] = [
  { value: 90, suffix: '%', label: 'Practical Hands-on Learning', sublabel: 'Everyday skills that matter' },
  { value: 50, suffix: '+', label: 'Essential Shortcut Keys', sublabel: 'Windows, Office & Web' },
  { value: 10, suffix: '%', label: 'Core Hardware Intro', sublabel: 'CPU, RAM, SSD & Ports' },
  { value: 100, suffix: '%', label: 'Beginner Friendly', sublabel: 'Step-by-step in Hindi & English' },
];

export const FORMATIONS: FormationInfo[] = [
  { id: 0, key: 'sphere', name: 'Sphere', description: 'Fibonacci spherical distribution with harmonic noise', colorHex: '#ff1a35' },
  { id: 1, key: 'helix', name: 'Helix', description: 'Triple-strand DNA helix with helical rotation', colorHex: '#00ffa3' },
  { id: 2, key: 'grid', name: 'Grid', description: 'Quantum undulating lattice plane with ripple waves', colorHex: '#f0f0f5' },
  { id: 3, key: 'torus', name: 'Torus', description: 'Trefoil mathematical ring in continuous deformation', colorHex: '#ff0040' },
  { id: 4, key: 'galaxy', name: 'Galaxy', description: 'Four-arm spiral galactic vortex with starry dispersion', colorHex: '#ffbf00' },
  { id: 5, key: 'vortex', name: 'Vortex', description: 'Hyperbolic singularity vortex drawing into the void', colorHex: '#c8ff00' },
];
